### ISSUE TITLE
How can i remove title bar buttons? 

### ISSUE THREAD

**Issue by BigLadDylan** [artsyfriedchicken/EdgyArc-fr#10]
![image](https://github.com/artsyfriedchicken/EdgyArc-fr/assets/76881322/123c4efd-82b1-4cdf-8801-4987e869345b)

I am on linux and I would like to know how i could get rid of titlebar buttons like close minimise etc..

cool theme btw!

**Comment by artsyfriedchicken** [comment]
I honestly have no clue! I havent tested it on linux yet! im still trying to get the bugs out of the macos version, and then ill need to fix both windows and linux specific bugs T___T

**Comment by artsyfriedchicken** [comment]
.titlebar-buttonbox-container {display:none !important} ? or something of that sort?

**Comment by BigLadDylan** [comment]
Sorry for late reply! I appreciate you getting back to me.

Im using the [hyprland](https://hyprland.org/) compositor and so i dont use window buttons. In all honesty I just switched to another arc theme... I really like this one though! 

Thanks for your help tho.

**Comment by johnhamelink** [comment]
So in order to remove the buttons, I had to:

Add this to the end of the config:
```css
        toolbar#nav-bar.browser-toolbar {
            padding-inline-end: 0 !important;
        }

        .titlebar-buttonbox-container {
            display:none !important;
            width: 0 !important;
        }

```

And modify the value of `--uc-window-control-btn` to `0px` (I edited the hide-tabs-bar.css file directly for this one because I struggled to find a CSS selector which would override the value).
