### ISSUE TITLE
1px wide white border on fullscreen

### ISSUE THREAD

**Issue by InternetNutzer** [artsyfriedchicken/EdgyArc-fr#28]
**Describe the bug**
Going into fullscreen leaves you with a white border, which can be distracting when watching videos that are rather dark

**To Reproduce**
1. Go to any video
2. Click on fullscreen
3. Look at the edges of screen

**Expected behavior**
The border to be removed when watching in fullscreen

**Screenshots**
https://i.imgur.com/Pokfj2S.png

**Desktop:**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 124.0.2 (64-bit)

**Additional context**
I've noticed this code snippet, which seems like it was supposed to be a workaround for this exact problem, but I was still experiencing the border
```css
/*remove 1px window border in fullscreen*/
  :root[inFullscreen]#main-window::before {
    opacity: 0 !important;
  }
```

love your rice, keep up the good work <3
